import time
import RPi.GPIO as GPIO
GPIO.setmode(GPIO.BOARD)
GPIO.setup(32, GPIO.OUT)
p = GPIO.PWM(32, 200)
p.start(0)
p.ChangeDutyCycle(0)
time.sleep(10)
p.ChangeDutyCycle(10)
time.sleep(10)
p.ChangeDutyCycle(20)
time.sleep(10)
p.ChangeDutyCycle(30)
time.sleep(10)
p.ChangeDutyCycle(40)
time.sleep(10)
p.ChangeDutyCycle(50)
time.sleep(10)
p.ChangeDutyCycle(60)
time.sleep(10)
p.ChangeDutyCycle(70)
time.sleep(10)
p.ChangeDutyCycle(80)
time.sleep(10)
p.ChangeDutyCycle(90)
time.sleep(10)
p.ChangeDutyCycle(93)
time.sleep(10)
p.stop()
GPIO.cleanup()
